### ISSUE TITLE
installation issues #2

### ISSUE THREAD

**Issue by janequist** [inveniosoftware/invenio-app-ils#764] opened 2020-03-09 04:32 UTC
Hello,

I've pulled the latest after the fix to #749 and downgraded my python to 3.5 as recommended.
But am getting other errors if I run the bootstrap script (after docker). Plz address.

We'd like to get a running version to evaluate if it meets our basic project requirements. It doesn't have to be super 100% stable. 

Thanks.
mj

--
ERROR: invenio-accounts 1.1.3 has requirement invenio-base>=1.2.2, but you'll have invenio-base 1.1.0 which is incompatible.
ERROR: invenio-accounts 1.1.3 has requirement invenio-i18n>=1.2.0, but you'll have invenio-i18n 1.1.1 which is incompatible. 

raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (invenio-i18n 1.1.1 (~/.virtualenvs/inv/lib/python3.5/site-packages), Requirement.parse('invenio-i18n>=1.2.0'), {'invenio-accounts'})

**Comment by ntarocco** [comment] 2020-04-02 09:30
@janequist I am so sorry, we did not see your issue here... there is an on-going process of fixing the underlying Invenio dependencies and we are working on it. We are committed of having an usable version of ILS in the coming days.

**Comment by janequist** [comment] 2020-04-04 03:11
Hello, no rush - plz first be safe during this pandemic ...

**Comment by ntarocco** [comment] 2020-04-05 14:09
The master branch should not build without issues in a new virtualenv.
You can see some doc (still under development) on how to install and run [here](https://invenioils.docs.cern.ch/quickstart/).
Feel free to share with us your opinion on the product, we are really interested to make this useful to other people too!

**Comment by janequist** [comment] 2020-05-01 01:51
Hi,
Thanks for creating the install doc. I was away due to the epidemic.
Today I tried to install and am getting some issues running the bootstrap script. It seems to have done the following:
...
Successfully installed invenio-accounts invenio-oauthclient
...
Successfully installed invenio-app-ils

But after that getting:

ERROR in app: Failed to initialize entry point: invenio_records_rest = invenio_records_rest.views:create_blueprint_from_app
Traceback (most recent call last):
  File "/Users/jquist/Dev/virtualenvs/my-site/lib/python3.5/site-packages/werkzeug/utils.py", line 576, in import_string
    module = __import__(module_name, globals(), locals(), [obj_name])
  File "/Users/jquist/Dev/invenio-app-ils-master/invenio_app_ils/records/loaders/__init__.py", line 16, in <module>
    from .schemas.json.series import SeriesSchemaV1
  File "/Users/jquist/Dev/invenio-app-ils-master/invenio_app_ils/records/loaders/schemas/json/series.py", line 14, in <module>
    from invenio_app_ils.documents.loaders.jsonschemas.document import AlternativeTitleSchema, \
  File "/Users/jquist/Dev/invenio-app-ils-master/invenio_app_ils/documents/loaders/__init__.py", line 10, in <module>
    from invenio_app_ils.records.loaders import ils_marshmallow_loader
ImportError: cannot import name 'ils_marshmallow_loader'

**Comment by ntarocco** [comment] 2020-05-01 10:18
Is this when you run the server, or installing? Our builds are passing in Travis now (see [here](https://travis-ci.org/github/inveniosoftware/invenio-app-ils/builds/681843048)) and we are actively developing from master without issues reported, so I am wondering if you maybe have a "dirty/broken" environment.
I would suggest to start from scratch and from a clean virtual env, or if you could let us know at which step you are encountering this issue.

**Comment by kvslee** [comment] 2020-05-04 07:34
I had the same error during installation, when I run ./script/bootstrap.

 ERROR in app: Failed to initialize entry point: invenio_records_rest = invenio_records_rest.views:create_blueprint_from_app
Traceback (most recent call last):
  File "c:\users\seong\anaconda3\envs\invenioils\lib\site-packages\werkzeug\utils.py", line 576, in import_string
    module = __import__(module_name, globals(), locals(), [obj_name])
  File "c:\dev\projects\invenioils\invenio_app_ils\records\loaders\__init__.py", line 16, in <module>
    from .schemas.json.series import SeriesSchemaV1
  File "c:\dev\projects\invenioils\invenio_app_ils\records\loaders\schemas\json\series.py", line 14, in <module>
    from invenio_app_ils.documents.loaders.jsonschemas.document import AlternativeTitleSchema, \
  File "c:\dev\projects\invenioils\invenio_app_ils\documents\loaders\__init__.py", line 10, in <module>
    from invenio_app_ils.records.loaders import ils_marshmallow_loader
ImportError: cannot import name 'ils_marshmallow_loader'

**Comment by ntarocco** [comment] 2020-05-04 08:59
@kvslee I just tried, right now, with a new clean virtual env, Python 3.6.7, and it worked.
Here my step:
* clone the repo
* create a new virtualenv with Python 3 and activate it
* `./scripts/bootstrap`

Questions:
* which Python version do you use?
* did you start from a clean/empty virtual env?
* isn't this issue happening when you run the Invenio web server, given the error?

**Comment by kvslee** [comment] 2020-05-05 03:07
@ntarocco I was using python 3.5.

I tried again with a clean/empty virtual env and the same Python version (3.6.7). I ended up with a different error. I attach a screenshot below. This error happens when I run ./scripts/bootstrap.

![image](https://user-images.githubusercontent.com/10362087/81031719-07ea4200-8e42-11ea-8f15-f7c712d3e0ea.png)

I got another error when I cloned the repository of invenio-app-ils.git. 
![image](https://user-images.githubusercontent.com/10362087/81031844-8515b700-8e42-11ea-833f-72fec42614f1.png)

**Comment by ntarocco** [comment] 2020-05-05 07:20
I see that you are using Windows from your logs, unfortunately we have never tested it on Windows and I am not sure Invenio will work nicely. You can join the Invenio support chat [here](gitter.im/inveniosoftware/invenio) and ask for help to see if anyone else has tried to install Invenio on Windows.

**Comment by ntarocco** [comment] 2020-05-05 16:36
@kvslee I was able to reproduce the issue in a Windows virtual machine: the issue was that there was a `__test__` folder that had a leading space at the end, not visible, a non compatible with Windows. I have removed the space. The git clone now succeeds for me. Sorry for the inconvenience.

**Comment by kvslee** [comment] 2020-05-05 19:58
@ntarocco Thank you so much for the update. I could clone the repo without any error. That's a good progress. However, I still see the same error when running ./scripts/bootstrap. It happens while building static assets.

![image](https://user-images.githubusercontent.com/10362087/81109501-0adf4400-8ecf-11ea-94f9-ed0f24b39abb.png)

The previous logs look good, except two errors. 

![image](https://user-images.githubusercontent.com/10362087/81109703-5a257480-8ecf-11ea-8e4a-6437f82f2d1a.png)
ERROR: awsebcli 3.10.5 requires botocore>=1.0.1, which is not installed.
ERROR: awsebcli 3.10.5 requires docker-py<=1.7.2,>=1.1.0, which is not installed.

Thank Nicola again.

**Comment by janequist** [comment] 2020-05-08 05:17
Hello,

Thanks for the pointers - after checking the Travis build I upgraded back to Python 3.6 (had downgraded before to fix earlier issue) and did a clean build coupla days back and got it working. So from my end, its no longer an issue now - you may close when its resolved for others.

Thanks.

**Comment by ntarocco** [comment] 2020-05-09 09:56
> @ntarocco Thank you so much for the update. I could clone the repo without any error. That's a good progress. However, I still see the same error when running ./scripts/bootstrap. It happens while building static assets.
> Thank Nicola again.

@kvslee if you just want to try out the product, it is not extremely important that it fails while building assets. Such assets are needed for the Invenio Admin panel and other advanced user settings, not needed to use the site and the backoffice app.
As a workaround, you can comment out [the last line](https://github.com/inveniosoftware/invenio-app-ils/blob/master/scripts/bootstrap#L14) from the script. Or keep the part `invenio collect -v`, but comment out the part `invenio webpack ...`.
Just make sure that the installation of Python requirements works and ignore that assets.

**Comment by kvslee** [comment] 2020-05-11 06:51
@ntarocco I find that subprocess.py has some reports of conflicts with Windows. I couldn't find how to fix this in this context.

**Comment by kvslee** [comment] 2020-06-21 01:51
The problem was that my console did not have npm installed. After installing npm, it built all requirements.

**Comment by ntarocco** [comment] 2020-06-30 07:47
Great that the issue has been fixed!

**Closed as completed by ntarocco** 2020-06-30 07:47 UTC
