### ISSUE TITLE
Backlog

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-ils#1] opened 2018-05-22 07:19 UTC
* Cookiecutter new instance, setup basic information
* Define the data model and create the new module repository for ILS
* Integrate the data model module in this instance.
* Setup files storage
* Create user/librarian/admin roles
* **Create extensive documentation**: how to use, how to customise

Front site:
* Customize home page: (responsive)
  * Create "front page collection"
  * Create sub-collections
  * Create menu
* Customize search: (responsive)
  * grid/list layout
  * row display
  * sorting
  * facets
  * pagination
* Customize record details page: (responsive)
  * different UI per type: book, volume, series with volumes, articles
  * show attached files
  * similar result section
  * share section
* Books suggestions: (responsive)
  * Define a customizable sequence of BookRequestSuggestion statuses
  * Create book request form to suggest a book and set it as `PENDING`
* Create a user profile page with his requests and statuses
* Help/FAQ pages

Back-office:
* Setup tools for back-office forms
* Form to create/edit/delete a simple book (responsive)
* Form to create/edit/delete a Series+Volumes (responsive)
* Files attachment
* ACL for books
* Create fixtures for demo data/user
* Suggested books:
  * Reject a book suggestion
  * Accept and create a book from a suggestion

User privacy:
* GDPR developer guide: https://techblog.bozho.net/gdpr-practical-guide-developers/

CERN CDS Overlay (to be moved):
* Create instance depending to overlay this instance
* Create the continuous integration DEV environment with local DB, ES, etc...
* Style home page
* Style search results
* Style record details page
* Style back-office forms
* Modify/add help/FAQ
* Test mobile visualization

**Comment by ludmilamarian** [comment] 2018-10-03 14:09
closing as duplicate of https://github.com/CERNDocumentServer/cds-books/issues/5

**Closed as completed by ludmilamarian** 2018-10-03 14:09 UTC
